#!/bin/bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";

HTPASSWD_FILE="$DOKKU_ROOT/$APP/HTPASSWD";
NGINX_CONF="$DOKKU_ROOT/$APP/nginx.conf";

if [[ -f "$HTPASSWD_FILE" ]]; then
  # update app nginx.conf with the security parameters
  perl -0777 -i -pe 's/server ?\{((\s|\S)*)\}/server \{\1  auth_basic \"Restricted\";\n  auth_basic_user_file $ARGV[0];\n\}/' $NGINX_CONF $HTPASSWD_FILE
fi
